const Experience = (props) => {
	return (
		<div className="py-8">
			<div className="xl:max-w-10xl">
				<h1 className="font-serif mb-6 text-3xl text-center lg:text-left md:text-4xl xl:text-4xl text-gray-800">About Me</h1>
				<p className="mb-4 font-sans text-gray-800 text-base xl:text-base">{"Since building my first website in 2010, I’ve had a burning passion for web development, which has evolved to include digital marketing and, most recently, artificial intelligence. I help companies navigate the interplay of these three."}</p>
				<p className="mb-4 font-sans text-gray-800 text-base xl:text-base">{"I can build systems from scratch, optimize what’s already there, or simply give my professional opinion on solving any web development, digital marketing, or AI-related problem."}</p>
				<p className="mb-4 font-sans text-gray-800 text-base xl:text-base">I’ve worked full-time remotely for over 14 years with clients from both America and Europe. No matter the time difference, I pride myself on getting the work done on time and mesh seamlessly with any team that values effective communication.</p>
				<p className="mb-8 font-sans text-gray-800 text-base xl:text-base">My roles as lead developer, web consultant, and advisor to companies in many different fields has helped me to think on my feet and solve problems fast. That's why I thrive in fast-paced environments with tight deadlines and high expectations.</p>
				<h2 className="mb-4 font-serif text-gray-800 text-2xl">Work Experience</h2>
				<p className="mb-6 font-sans text-gray-800 text-base xl:text-base">Over the years I’ve had the pleasure to work with some truly great companies and clients.</p>
				<h2 className="mb-4 font-serif text-gray-800 text-lg md:text-xl">Too Pixel</h2>
				<p className="mb-4 font-sans text-gray-800 text-base xl:text-base">Too Pixel was a traditional web design agency in Geneva, Switzerland, focused on providing custom-built solutions for their clients. After becoming one of their first hires, I was soon promoted to the lead developer role and managed projects for brands including: CERN, Notz Stucki, EPFL, Newby of London, and much more.</p>
				<p className="mb-6 font-sans text-gray-800 text-base xl:text-base">My 7 years working full-time remotely for Too Pixel helped me master my core skill of web development. The traditional agency atmosphere also helped me learn how to work effectively as part of a team with high-stakes projects on the line. I had to pitch ideas, implement feedback, and shift gears quickly when plans had to change.</p>
				<h2 className="mb-4 font-serif text-gray-800 text-lg md:text-xl">Single Grain</h2>
				<p className="mb-4 font-sans text-gray-800 text-base xl:text-base">Since 2009, Single Grain has been a well-regarded digital marketing agency with clients like Uber, Amazon, Lyft, SalesForce, and AirBnB. I was first hired to manage all the web properties of the company and report directly to the CEO, Eric Siu, known best for his Marketing School podcast with Neil Patel.</p>
				<p className="mb-4 font-sans text-gray-800 text-base xl:text-base">My core expertise at the time was web development, but being surrounded by highly skilled marketers, I quickly learned a lot more about digital marketing. I was soon invited to join the internal Growth Team, responsible for scaling Eric’s personal brand and new business ventures. These projects were built in a ‘lean startup’ mentality, requiring me to learn new skills fast, and find solutions to problems working with limited resources.</p>
				<p className="mb-4 font-sans text-gray-800 text-base xl:text-base">In line with the evolving technological landscape, I am currently at the helm of our artificial intelligence transformation initiatives. Both within Single Grain and for our diverse roster of clients, I am spearheading the integration of AI into our existing workflows and service offerings.</p>
				<h2 className="mb-4 font-serif text-gray-800 text-lg md:text-xl">Generation Genius</h2>
				<p className="mb-4 font-sans text-gray-800 text-base xl:text-base">Generation Genius is a Los Angeles-based startup building an educational streaming service teaching kids about science &amp; math, while also offering a range of home science kits for hands-on exploration.</p>
				<p className="mb-6 font-sans text-gray-800 text-base xl:text-base">As the first full-time developer hired, my core responsibilities encompassed enhancing the website, designing and implementing new features, as well as addressing issues within the legacy systems. In my 2 years leading the development growth scaled from 250K to 1.25M visitors per month along with a 6X increase in revenue. After this successful period, I transitioned to the role of a consulting developer. My responsibilities include strategic decision-making, assisting with developer recruitment, and resolving critical issues.</p>
				<p className="mb-6 font-sans text-gray-800 text-base xl:text-base">Generation Genius, now not only ranked the <strong>#1 Fastest Growing Education Company in America</strong> on the 2022 Inc5000 list due to a staggering revenue growth rate of 4,891% from 2018 to 2021, has also garnered the tremendous honor of being named to TIME Magazine's list of <strong>100 Most Influential Companies</strong> in the World for 2023. This prestigious recognition has us sharing the list with household names such as Apple, SpaceX, OpenAI, and Nvidia.</p>
			</div>
		</div>
	);
};

export default Experience;